import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const videoRef = useRef(null);

  useEffect(() => {
    // videoRef.current.playbackRate = 0.5;
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <img
          src="/universe.jpg"
          style={{
            width: "100vw",
            height: "100vh",
            position: "fixed",
            zIndex: "-1",
            objectFit: "cover",
          }}
        ></img> */}
        <span
          style={{
            width: "100vw",
            height: "100vh",
            position: "fixed",
            zIndex: "-1",
          }}
        >
          {Array.from({ length: 10 }, (_, i) => i + 1).map((item) => {
            return <div key={item} className="firefly"></div>;
          })}
          {/* <img
            src="/earth.gif"
            className="object-cover w-full absolute bottom-0 xs:transform-none sm:translate-y-[60%] z-[1]"
            style={{
              WebkitMaskImage: "url(circle.svg)",
              WebkitMaskSize: "cover",
            }}
          ></img> */}
          <video
            ref={videoRef}
            autoPlay
            muted
            // loop
            className="w-full object-cover h-full absolute z-[1]"
          >
            <source src="/splash2.mp4"></source>
          </video>
          <span className="left-bounce text-4xl md:text-5xl absolute mt-[40vh] w-full text-center z-[2]">
            <span className="text-white">
              Digital <span className="text-blue-800">Asset</span> Foundry
            </span>
          </span>
          <p className="vegas-shadow text-slate-200 text-xl lg:text-2xl z-[2] w-full text-center mt-[60vh] absolute right-bounce delay-300 tracking-wider">
            {"BRIDGING"}
            <br />
            the
            <br />
            {"PHYSICAL WORLD"}
            <br />
            {"OF REAL ESTATE "}
            <br />
            and the
            <br />
            {"DIGITAL WORLD"}
            <br />
            {"OF BLOCKCHAIN"}
          </p>
        </span>
      </main>
    </div>
  );
}
